
/*******************************************************************
*
* CAUTION: This file is automatically generated by HSI.
* Version: 2021.2
* DO NOT EDIT.
*
* Copyright (C) 2010-2021 Xilinx, Inc. All Rights Reserved.
* SPDX-License-Identifier: MIT 

* 
* Description: Driver configuration
*
*******************************************************************/

#include "xparameters.h"
#include "xgpio.h"

/*
* The configuration table for devices
*/

XGpio_Config XGpio_ConfigTable[XPAR_XGPIO_NUM_INSTANCES] =
{
	{
		XPAR_AXI_GPIO_CONTROL_DEVICE_ID,
		XPAR_AXI_GPIO_CONTROL_BASEADDR,
		XPAR_AXI_GPIO_CONTROL_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_CONTROL_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_POLYNOMIAL_DEVICE_ID,
		XPAR_AXI_GPIO_POLYNOMIAL_BASEADDR,
		XPAR_AXI_GPIO_POLYNOMIAL_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_POLYNOMIAL_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_RESULT_DEVICE_ID,
		XPAR_AXI_GPIO_RESULT_BASEADDR,
		XPAR_AXI_GPIO_RESULT_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_RESULT_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_BTNS_DEVICE_ID,
		XPAR_AXI_GPIO_BTNS_BASEADDR,
		XPAR_AXI_GPIO_BTNS_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_BTNS_IS_DUAL
	},
	{
		XPAR_AXI_GPIO_LED_DEVICE_ID,
		XPAR_AXI_GPIO_LED_BASEADDR,
		XPAR_AXI_GPIO_LED_INTERRUPT_PRESENT,
		XPAR_AXI_GPIO_LED_IS_DUAL
	}
};


