# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/macie/Desktop/testcases/mentor_security_trng_2.0/arty_z7_design/arty_z7_design.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_polynomial_0/design_1_axi_gpio_polynomial_0.xci
# IP: The module: 'design_1_axi_gpio_polynomial_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/macie/Desktop/testcases/mentor_security_trng_2.0/arty_z7_design/arty_z7_design.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_polynomial_0/design_1_axi_gpio_polynomial_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_polynomial_0'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/macie/Desktop/testcases/mentor_security_trng_2.0/arty_z7_design/arty_z7_design.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_polynomial_0/design_1_axi_gpio_polynomial_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_polynomial_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/macie/Desktop/testcases/mentor_security_trng_2.0/arty_z7_design/arty_z7_design.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_polynomial_0/design_1_axi_gpio_polynomial_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_polynomial_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: C:/Users/macie/Desktop/testcases/mentor_security_trng_2.0/arty_z7_design/arty_z7_design.srcs/sources_1/bd/design_1/ip/design_1_axi_gpio_polynomial_0/design_1_axi_gpio_polynomial_0.xci
# IP: The module: 'design_1_axi_gpio_polynomial_0' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/macie/Desktop/testcases/mentor_security_trng_2.0/arty_z7_design/arty_z7_design.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_polynomial_0/design_1_axi_gpio_polynomial_0_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_polynomial_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/macie/Desktop/testcases/mentor_security_trng_2.0/arty_z7_design/arty_z7_design.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_polynomial_0/design_1_axi_gpio_polynomial_0_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_polynomial_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: c:/Users/macie/Desktop/testcases/mentor_security_trng_2.0/arty_z7_design/arty_z7_design.gen/sources_1/bd/design_1/ip/design_1_axi_gpio_polynomial_0/design_1_axi_gpio_polynomial_0.xdc
# XDC: The top module name and the constraint reference have the same name: 'design_1_axi_gpio_polynomial_0'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
