# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# XDC: imports/Xilinx/Cmod-A7-Master IMPROVED.xdc

# Block Designs: bd/design_1/design_1.bd
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1 || ORIG_REF_NAME==design_1} -quiet] -quiet

# IP: bd/design_1/ip/design_1_latch_n_0_0/design_1_latch_n_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_latch_n_0_0 || ORIG_REF_NAME==design_1_latch_n_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_SPI_0_0/design_1_SPI_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_SPI_0_0 || ORIG_REF_NAME==design_1_SPI_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_clk_wiz_0_0/design_1_clk_wiz_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_clk_wiz_0_0 || ORIG_REF_NAME==design_1_clk_wiz_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_pulse_formatter_0_0/design_1_pulse_formatter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_pulse_formatter_0_0 || ORIG_REF_NAME==design_1_pulse_formatter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ready_counter_0_0/design_1_ready_counter_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ready_counter_0_0 || ORIG_REF_NAME==design_1_ready_counter_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_ro_injector_0_0/design_1_ro_injector_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_ro_injector_0_0 || ORIG_REF_NAME==design_1_ro_injector_0_0} -quiet] -quiet

# IP: bd/design_1/ip/design_1_r2o_ring_gen_64_0_0/design_1_r2o_ring_gen_64_0_0.xci
set_property KEEP_HIERARCHY SOFT [get_cells -hier -filter {REF_NAME==design_1_r2o_ring_gen_64_0_0 || ORIG_REF_NAME==design_1_r2o_ring_gen_64_0_0} -quiet] -quiet

# XDC: c:/Users/mtrawka/Documents/aio/testcases/mentor/security/proof_of_concept/vivado_design/random_number_gen_RTL/random_number_gen_RTL.gen/sources_1/bd/design_1/design_1_ooc.xdc
